apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: nitingoyal
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: nitingoyal/samplenodeapp:feature
        envFrom:
        - configMapRef:
            name: node-app-config
        ports:
        - containerPort: 7100

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: nitingoyal
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7100
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-app-config
  namespace: nitingoyal
data:
  Test_Key1: "Value1"
  Test_Key2: "Value2"